/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    records: Record;
    media: Media;
    categories: Category;
    types: Type;
    papers: Paper;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Record {
  id: string;
  title: string;
  category: string;
  type: string;
  metaDescription?: string | null;
  language: 'zh-tw' | 'en';
  url: string;
  richText?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  slug: string;
  isRecordShow: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename: string;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Category {
  id: string;
  displayName: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
export interface Type {
  id: string;
  displayName: string;
  value: string;
  updatedAt: string;
  createdAt: string;
}
export interface Paper {
  id: string;
  doi?: string | null;
  url: string;
  fileUrl?: string | null;
  title: string;
  journal: string;
  publishedAt: string;
  substance: (
    | '2c-b'
    | '5-meo-dmt'
    | 'amanita-muscaria'
    | 'ayahuasca'
    | 'cannabis'
    | 'dmt'
    | 'doi'
    | 'ghb'
    | 'ibogaine'
    | 'ketamine'
    | 'lsa'
    | 'lsd'
    | 'lsd-analogs'
    | 'mdma'
    | 'mescaline'
    | 'peyote'
    | 'pcp'
    | 'psilocybin'
    | 'salvia'
    | 'unspecified'
  )[];
  abstract: {
    [k: string]: unknown;
  }[];
  authorsField?:
    | {
        author?: string | null;
        id?: string | null;
      }[]
    | null;
  summaryField?:
    | {
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  summaryZhTwField?:
    | {
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  keywordsField?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  isVectorized?: boolean | null;
  viewCount: number;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}